구조 정리
Shubidumdu/js-13k-2022 pull request #1
Opened 2022-08-21 06:25 UTC by neokkk

## 작업 내용
- html에 직접 캔버스 태그를 바인딩하고 해당 인스턴스에 결합도가 높은 함수를 매번 생성하는 대신, 중복을 줄이고 js에서 한 번에 처리하게 해 재사용성을 높이도록 했습니다.
- 전역에서 사용할 저장소를 생성했습니다.
- GameScene이 여러 의미로 해석될 여지가 있는 것 같아 PlayScene으로 이름을 변경했습니다.
- 캔버스 클릭 이벤트를 추가했습니다.

## 체크 리스트
- 일단 클릭 이벤트가 필요할 것 같아서 추가하긴 했는 필요 없을 것 같으면 제거해도 될 것 같습다.

2022-08-21 07:55 UTC, Shubidumdu requested changes
제가 습관으로 master에 직접 push를 했더니 충돌이 나는군여ㅠ 죄송합니다.
다음엔 저도 직접 머지 않고 제대로 PR을 올리겠습니다. 🙇

2022-08-21 07:55 UTC, Shubidumdu commented on src/game.ts
> +          break;
현재 프로젝트의 `typesccript`, `ts-loader` 패키지가 꽤 구버전이라, 요 부분에서 디스트럭처링된 `type`, `payload`에 대한 타입 추론이 똑똑하게 이루어지지 않아 빌드 시 에러가 발생하네요. 혹시 하시는 김에 다음을 통해서 업데이트 시켜주실 수 있을까용?
```
yarn add --dev ts-loader typescript
```

2022-08-21 07:55 UTC, Shubidumdu commented on src/store/index.ts
> +import { default as state } from './modules/state';
전역 상태를 다룰 store를 따로 두는 것은 좋은 생각인 것 같습니다. 👍 
근데 여기에서 저는 `modules` 폴더의 역할이 불분명해 보인다는 느낌을 받는데, 그냥 없애고 동일한 깊이에 두는 것이 어떤가요? 🤔

2022-08-21 07:55 UTC, Shubidumdu commented on src/store/modules/state.ts
> +  soundActive: boolean,
`soundActive`라는 명칭이 제밥 모호하게 해석될 여지가 있을 것 같습니다. 
(일단 저는 이름만 봤을 때 이게 활성화 사운드(ex. 뾰로롱 소리? 같은)를 재생하는 함수라고 생각했습니다.)
적어도 이것이 boolean이라는 점을 한눈에 알 수 있도록, `isSoundOn` 정도의 이름은 어떨지 제안드려봅니다. :)

2022-08-21 07:55 UTC, Shubidumdu commented on src/store/modules/state.ts
> +const state = new Map<keyof State, State[keyof State]>();
위의 canvas의 경우에는 어떤 키든 value가 canvas 요소 일 것이라, Map을 사용해도 문제가 없을 것인데, 요 state의 경우에는 들어오는 value 자체에 자유도를 부여하고 있는 상황이기 때문에, 아래처럼 예상되는 문제가 좀 있습니다.

```ts
type State = {
  soundActive: boolean,
  otherProp: string,
};

// ...

state.get('otherProp'); // 반환 타입이 boolean | string임.
```

2022-08-21 07:55 UTC, Shubidumdu commented on src/scenes/title.ts
> +  }
[autoplay policy](https://developer.chrome.com/blog/autoplay/)에 의해, 최초에 유저 인터랙션 없이는 AudioContext를 재생할 수 없는 상태이기 때문에, 요게 기본값이 `false`여야 자연스럽습니다.

2022-08-21 08:22 UTC, neokkk commented on src/game.ts
> +          break;
오 넹 하는 김에 jest도 업데이트 할게용

2022-08-21 08:36 UTC, neokkk commented on src/store/modules/state.ts
> +const state = new Map<keyof State, State[keyof State]>();
그러게요. 들어가는 타입이 다르니까 Map을 쓰긴 애매하네요. 명확히 getter setter가 구분되었으면 해서 저렇게 한 것인데, 그냥 일반 객체로 쓰는게 좋을 것 같아요. [위에 의견 주신 거](https://github.com/Shubidumdu/js-13k-2022/pull/1#discussion_r950801009)랑 같이 생각해보면, 일반 state는 flat하게 가고, canvas와 같이 Map으로 각자의 영역을 가지고 있는 애들은 namespace를 주면 어떨까요? (modules 하위에 위치)

2022-08-21 08:36 UTC, neokkk commented on src/scenes/title.ts
> +  }
굿굿

2022-08-21 16:50 UTC, Shubidumdu commented on src/store/modules/state.ts
> +const state = new Map<keyof State, State[keyof State]>();
그냥 캔버스 맵을 `/canvas.ts`에서 내보내도록 하고, modules는 없애는게 어떨까요? 여전히 의미를 잘 모르겠습니다.
캔버스 맵 자체는 그냥 레이어들을 담고 있는 역할일 뿐이라, 이건 store에 있기도 애매하지 않나 싶은 생각이 드네요. 💭

2022-08-22 13:14 UTC, neokkk commented on src/store/modules/state.ts
> +const state = new Map<keyof State, State[keyof State]>();
음 그러게요 canvas는 별도로 두면 좋겠는데, cache는 그렇고.. 어떻게 분리하면 좋을까요?

2022-08-23 09:47 UTC, Shubidumdu approved these changes

2022-08-23 09:47 UTC, merged